///// ESTA BASE DE DATOS GUARDA EL HISTORIAL DE USO DE LOS ReAbs GUARDADOS EN ReAb-Database.ts 

//// ESTA BASE DE DATOS SIRVE PARA TOMAR DESICIONES Y PARA EL POSTERIOR ANALISIS DE DATOS

//// EN ESTA SE GUARDAN LOS ULTIMOS 30/100 ESTÍMULOS

//// SE GUARDA EL ReAb(s) USADO(S), EL EXERSICE DESINGS USADO, LO QUE SE CONTESTO CORRECTO Y LO QUE SE CONTESTO ERRONEO, LOS METODOS MNEMOTECNICOS USADOS 